spring:
  datasource:
    url: jdbc:h2:mem:petshop

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
#      schema-locations: classpath:schema.sql